apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: k8s-ws
spec:
  backend:
    serviceName: mysvc
    servicePort: 80
    - path: /hello
      backend:
        serviceName: hello
        servicePort: 80

